In [2]:
import numpy as np
import time

# creating large list and array
size = 100000000
list_data = list(range(size))
array_data = np.array(range(size))

# timing of the list operation
start_time = time.time()
list_sum = sum(list_data)
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken by list: {list_time} seconds")

# timing of the array operation
start_time = time.time()
list_sum = np.sum(array_data)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken by array: {array_time} seconds")


Time taken by list: 3.441396951675415 seconds
Time taken by array: 0.05884671211242676 seconds


### In NumPy array, array is homogeneous

In [3]:
import numpy as np
ar = np.array([3,5,4,5,9.0])

In [4]:
print(type(ar[0]))

<class 'numpy.float64'>


In [5]:
ar
# numpy gives priority to floats because they can handle both whole numbers and decimal numbers

array([3., 5., 4., 5., 9.])

# Creating numpy array

In [6]:
import numpy as np
a = np.array([3,4,5])
a

array([3, 4, 5])

In [7]:
type(a)

numpy.ndarray

In [8]:
# In Numpy, ndarray is a class, and every array you create using Numpy is an instance of the ndarray class
zero = np.array(8)
zero

array(8)

In [9]:
zero.ndim

0

In [10]:
zero.shape

()

In [11]:
one = np.array([3,4,6,4,5])
one

array([3, 4, 6, 4, 5])

In [12]:
one.ndim

1

In [13]:
one.shape

(5,)

In [14]:
two = np.array([[3,4,5], [8,9,10]])
two

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [15]:
two.ndim

2

In [16]:
two.shape

(2, 3)

In [17]:
three = np.array([[[1,2,4], [4,53,4]], [[4,55,6],[7,7,58]]])
three

array([[[ 1,  2,  4],
        [ 4, 53,  4]],

       [[ 4, 55,  6],
        [ 7,  7, 58]]])

In [18]:
three.ndim

3

In [19]:
three.shape
# tensor - arrays with three or more dimensions

(2, 2, 3)

In [20]:
ara = np.arange(8) # arange function makes arrays with numbers that are evenly spaced within a set range
ara

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
ara1 = np.arange(1,8)
ara1

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
ara2 = np.arange(1,11,2)
ara2

array([1, 3, 5, 7, 9])

In [23]:
ara2 = np.arange(3,21,4)
ara2

array([ 3,  7, 11, 15, 19])

In [24]:
re = np.arange(1,21).reshape(4,5)
re

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
re1 = np.arange(1,25).reshape(6,4)
re1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [26]:
re2 = np.arange(1,25).reshape(2,4,3)
re2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [27]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
one = np.ones((4,6))
one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
lin = np.linspace(1,10,5)
lin # creates an array with 5 numbers between 1 and 10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [30]:
lin1 = np.linspace(3,20,7,dtype=int)
lin1

array([ 3,  5,  8, 11, 14, 17, 20])

In [31]:
rn = np.random.random((3,4)) # creates a 2-D array with 3 rows and 4 columns where each element ia a random float between 0 and 1
rn

array([[0.26976849, 0.55055764, 0.79052891, 0.34489851],
       [0.31781889, 0.12384164, 0.97474273, 0.94328715],
       [0.04216481, 0.28747958, 0.19557047, 0.21540192]])

In [32]:
rn1 = np.random.random((6,3,2))
rn1

array([[[0.2166594 , 0.94571092],
        [0.42841442, 0.98634285],
        [0.8233304 , 0.16720675]],

       [[0.84095767, 0.37223062],
        [0.42897559, 0.02732145],
        [0.16219953, 0.87393567]],

       [[0.62591728, 0.02857552],
        [0.9280765 , 0.91264186],
        [0.79401699, 0.64193934]],

       [[0.59496174, 0.16959919],
        [0.10204698, 0.63095677],
        [0.22372963, 0.20228318]],

       [[0.29522393, 0.4944634 ],
        [0.01982854, 0.00701901],
        [0.04309797, 0.06490139]],

       [[0.03506816, 0.40094521],
        [0.88612613, 0.34657546],
        [0.60521649, 0.58749697]]])

In [33]:
rin = np.random.randint(1,40,12) # 12 random integers between 1 and 40
rin

array([25, 37, 10, 22,  6, 14, 23,  1, 28, 12, 31,  2], dtype=int32)

In [34]:
rint = np.random.randint(1,150,(2,3))
rint

array([[ 34, 132,  66],
       [103,  23, 123]], dtype=int32)

In [35]:
rint1 = np.random.randint(110,200,(5,2,3))
rint1

array([[[183, 119, 194],
        [139, 123, 171]],

       [[134, 187, 135],
        [141, 163, 163]],

       [[193, 128, 194],
        [172, 161, 148]],

       [[121, 128, 152],
        [118, 132, 198]],

       [[155, 128, 112],
        [120, 146, 116]]], dtype=int32)

## Array Attribute

In [36]:
arr = np.arange(1,25).reshape(3,8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.ndim

2

In [38]:
arr.shape

(3, 8)

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr.size # total number of elements

24

In [41]:
arr.itemsize # each integer occupies 8 bytes

8

In [42]:
arr.nbytes # total memory size in bytes

192

In [43]:
arr2 = np.array([23,4,5,5,8.7,8])
arr2

array([23. ,  4. ,  5. ,  5. ,  8.7,  8. ])

In [44]:
arr2.dtype

dtype('float64')

In [45]:
arr2.size

6

In [46]:
arr2.itemsize

8

In [47]:
arr2.nbytes
# all attributes are part of ndarray class

48

# Changing Datatype

In [48]:
a3 = np.array([3,4,5,6,8.0,5,6,7])
a3

array([3., 4., 5., 6., 8., 5., 6., 7.])

In [51]:
a3.astype("int") # astype() method allows you to convert an array to a different data type

array([3, 4, 5, 6, 8, 5, 6, 7])

In [52]:
a4 = np.array([93,54,75,86,8,5,6,79])
a4

array([93, 54, 75, 86,  8,  5,  6, 79])

In [53]:
a4.astype("float")

array([93., 54., 75., 86.,  8.,  5.,  6., 79.])

# Array Operations

In [55]:
import numpy as np
a1 = np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
a2 = np.arange(11,21)
a2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### scalar operation