In [2]:
import numpy as np
import time

# creating large list and array
size = 100000000
list_data = list(range(size))
array_data = np.array(range(size))

# timing of the list operation
start_time = time.time()
list_sum = sum(list_data)
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken by list: {list_time} seconds")

# timing of the array operation
start_time = time.time()
list_sum = np.sum(array_data)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken by array: {array_time} seconds")


Time taken by list: 2.7544426918029785 seconds
Time taken by array: 0.10695052146911621 seconds


### In NumPy array, array is homogeneous

In [3]:
import numpy as np
ar = np.array([3,5,4,5,9.0])

In [4]:
print(type(ar[0]))

<class 'numpy.float64'>


In [5]:
ar
# numpy gives priority to floats because they can handle both whole numbers and decimal numbers

array([3., 5., 4., 5., 9.])

# Creating numpy array

In [6]:
import numpy as np
a = np.array([3,4,5])
a

array([3, 4, 5])

In [7]:
type(a)

numpy.ndarray

In [8]:
# In Numpy, ndarray is a class, and every array you create using Numpy is an instance of the ndarray class
zero = np.array(8)
zero

array(8)

In [9]:
zero.ndim

0

In [10]:
zero.shape

()

In [11]:
one = np.array([3,4,6,4,5])
one

array([3, 4, 6, 4, 5])

In [12]:
one.ndim

1

In [13]:
one.shape

(5,)

In [14]:
two = np.array([[3,4,5], [8,9,10]])
two

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [15]:
two.ndim

2

In [16]:
two.shape

(2, 3)

In [17]:
three = np.array([[[1,2,4], [4,53,4]], [[4,55,6],[7,7,58]]])
three

array([[[ 1,  2,  4],
        [ 4, 53,  4]],

       [[ 4, 55,  6],
        [ 7,  7, 58]]])

In [18]:
three.ndim

3

In [19]:
three.shape
# tensor - arrays with three or more dimensions

(2, 2, 3)

In [21]:
ara = np.arange(8) # arange function makes arrays with numbers that are evenly spaced within a set range
ara

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
ara1 = np.arange(1,8)
ara1

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
ara2 = np.arange(1,11,2)
ara2

array([1, 3, 5, 7, 9])

In [25]:
ara2 = np.arange(3,21,4)
ara2

array([ 3,  7, 11, 15, 19])

In [26]:
re = np.arange(1,21).reshape(4,5)
re

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
re1 = np.arange(1,25).reshape(6,4)
re1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [28]:
re2 = np.arange(1,25).reshape(2,4,3)
re2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [29]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
one = np.ones((4,6))
one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
lin = np.linspace(1,10,5)
lin # creates an array with 5 numbers between 1 and 10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
lin1 = np.linspace(3,20,7,dtype=int)
lin1

array([ 3,  5,  8, 11, 14, 17, 20])

In [35]:
rn = np.random.random((3,4)) # creates a 2-D array with 3 rows and 4 columns where each element ia a random float between 0 and 1
rn

array([[0.24244924, 0.61249417, 0.84490428, 0.70161516],
       [0.81665873, 0.95863806, 0.09152436, 0.64802819],
       [0.51776182, 0.85818501, 0.97844233, 0.23881998]])

In [36]:
rn1 = np.random.random((6,3,2))
rn1

array([[[0.77742286, 0.58140269],
        [0.72019163, 0.82605503],
        [0.96567727, 0.14711522]],

       [[0.31460824, 0.27928688],
        [0.93176353, 0.15955625],
        [0.96527686, 0.15812941]],

       [[0.87096777, 0.62396089],
        [0.65151689, 0.60063006],
        [0.02085561, 0.6812621 ]],

       [[0.97671366, 0.00211618],
        [0.51043186, 0.34627582],
        [0.84251052, 0.31878083]],

       [[0.40025205, 0.11182688],
        [0.29366699, 0.4329582 ],
        [0.73917864, 0.61518998]],

       [[0.35381716, 0.64010635],
        [0.6402426 , 0.4342821 ],
        [0.03229233, 0.35969026]]])

In [37]:
rin = np.random.randint(1,40,12) # 12 random integers between 1 and 40
rin

array([ 5, 38, 14,  4, 39, 18, 31, 36, 15,  4,  9, 15], dtype=int32)

In [38]:
rint = np.random.randint(1,150,(2,3))
rint

array([[134,  17,  52],
       [ 30,  80,  53]], dtype=int32)

In [39]:
rint1 = np.random.randint(110,200,(5,2,3))
rint1

array([[[182, 159, 191],
        [121, 175, 161]],

       [[125, 143, 144],
        [169, 195, 140]],

       [[174, 129, 189],
        [133, 132, 133]],

       [[166, 177, 161],
        [157, 125, 181]],

       [[178, 139, 115],
        [155, 127, 125]]], dtype=int32)