In [1]:
import numpy as np
import time

# creating large list and array
size = 100000000
list_data = list(range(size))
array_data = np.array(range(size))

# timing of the list operation
start_time = time.time()
list_sum = sum(list_data)
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken by list: {list_time} seconds")

# timing of the array operation
start_time = time.time()
list_sum = np.sum(array_data)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken by array: {array_time} seconds")


Time taken by list: 2.9325852394104004 seconds
Time taken by array: 0.12216472625732422 seconds


### In NumPy array, array is homogeneous

In [2]:
import numpy as np
ar = np.array([3,5,4,5,9.0])

In [3]:
print(type(ar[0]))

<class 'numpy.float64'>


In [4]:
ar
# numpy gives priority to floats because they can handle both whole numbers and decimal numbers

array([3., 5., 4., 5., 9.])

# Creating numpy array

In [1]:
import numpy as np
a = np.array([3,4,5])
a

array([3, 4, 5])

In [2]:
type(a)

numpy.ndarray

In [4]:
# In Numpy, ndarray is a class, and every array you create using Numpy is an instance of the ndarray class
zero = np.array(8)
zero

array(8)

In [5]:
zero.ndim

0

In [7]:
zero.shape

()

In [9]:
one = np.array([3,4,6,4,5])
one

array([3, 4, 6, 4, 5])

In [10]:
one.ndim

1

In [11]:
one.shape

(5,)

In [12]:
two = np.array([[3,4,5], [8,9,10]])
two

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [13]:
two.ndim

2

In [14]:
two.shape

(2, 3)

In [15]:
three = np.array([[[1,2,4], [4,53,4]], [[4,55,6],[7,7,58]]])
three

array([[[ 1,  2,  4],
        [ 4, 53,  4]],

       [[ 4, 55,  6],
        [ 7,  7, 58]]])

In [16]:
three.ndim

3

In [17]:
three.shape

(2, 2, 3)