In [1]:
import numpy as np
import time

# creating large list and array
size = 100000000
list_data = list(range(size))
array_data = np.array(range(size))

# timing of the list operation
start_time = time.time()
list_sum = sum(list_data)
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken by list: {list_time} seconds")

# timing of the array operation
start_time = time.time()
list_sum = np.sum(array_data)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken by array: {array_time} seconds")


Time taken by list: 2.913935661315918 seconds
Time taken by array: 0.06310796737670898 seconds


### In NumPy array, array is homogeneous

In [2]:
import numpy as np
ar = np.array([3,5,4,5,9.0])

In [3]:
print(type(ar[0]))

<class 'numpy.float64'>


In [4]:
ar
# numpy gives priority to floats because they can handle both whole numbers and decimal numbers

array([3., 5., 4., 5., 9.])

# Creating numpy array

In [5]:
import numpy as np
a = np.array([3,4,5])
a

array([3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [7]:
# In Numpy, ndarray is a class, and every array you create using Numpy is an instance of the ndarray class
zero = np.array(8)
zero

array(8)

In [8]:
zero.ndim

0

In [9]:
zero.shape

()

In [10]:
one = np.array([3,4,6,4,5])
one

array([3, 4, 6, 4, 5])

In [11]:
one.ndim

1

In [12]:
one.shape

(5,)

In [13]:
two = np.array([[3,4,5], [8,9,10]])
two

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [14]:
two.ndim

2

In [15]:
two.shape

(2, 3)

In [16]:
three = np.array([[[1,2,4], [4,53,4]], [[4,55,6],[7,7,58]]])
three

array([[[ 1,  2,  4],
        [ 4, 53,  4]],

       [[ 4, 55,  6],
        [ 7,  7, 58]]])

In [17]:
three.ndim

3

In [18]:
three.shape
# tensor - arrays with three or more dimensions

(2, 2, 3)

In [19]:
ara = np.arange(8) # arange function makes arrays with numbers that are evenly spaced within a set range
ara

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
ara1 = np.arange(1,8)
ara1

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
ara2 = np.arange(1,11,2)
ara2

array([1, 3, 5, 7, 9])

In [22]:
ara2 = np.arange(3,21,4)
ara2

array([ 3,  7, 11, 15, 19])

In [23]:
re = np.arange(1,21).reshape(4,5)
re

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
re1 = np.arange(1,25).reshape(6,4)
re1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [25]:
re2 = np.arange(1,25).reshape(2,4,3)
re2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [26]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
one = np.ones((4,6))
one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
lin = np.linspace(1,10,5)
lin # creates an array with 5 numbers between 1 and 10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
lin1 = np.linspace(3,20,7,dtype=int)
lin1

array([ 3,  5,  8, 11, 14, 17, 20])

In [30]:
rn = np.random.random((3,4)) # creates a 2-D array with 3 rows and 4 columns where each element ia a random float between 0 and 1
rn

array([[0.15767831, 0.16137673, 0.3785862 , 0.70339834],
       [0.45314408, 0.85535147, 0.14070604, 0.01569795],
       [0.06171199, 0.62554943, 0.77721795, 0.33600436]])

In [31]:
rn1 = np.random.random((6,3,2))
rn1

array([[[0.03801785, 0.81804994],
        [0.74487146, 0.68137665],
        [0.66112008, 0.70457561]],

       [[0.60177717, 0.12531972],
        [0.86383797, 0.31870111],
        [0.26865497, 0.19047797]],

       [[0.02918855, 0.7197671 ],
        [0.15628448, 0.80525413],
        [0.33001835, 0.22263006]],

       [[0.96631108, 0.85574595],
        [0.52353338, 0.5027213 ],
        [0.09049109, 0.11890047]],

       [[0.38092094, 0.14552656],
        [0.66166385, 0.9151007 ],
        [0.14866009, 0.88481874]],

       [[0.87220226, 0.7593473 ],
        [0.69132738, 0.63586289],
        [0.87127298, 0.21459944]]])

In [32]:
rin = np.random.randint(1,40,12) # 12 random integers between 1 and 40
rin

array([36, 24, 20, 38, 36, 19,  2, 23,  8, 20, 12, 38], dtype=int32)

In [33]:
rint = np.random.randint(1,150,(2,3))
rint

array([[105, 144,  51],
       [ 19, 114,  64]], dtype=int32)

In [34]:
rint1 = np.random.randint(110,200,(5,2,3))
rint1

array([[[183, 193, 175],
        [114, 115, 197]],

       [[153, 152, 195],
        [184, 115, 186]],

       [[123, 113, 145],
        [149, 155, 195]],

       [[155, 194, 133],
        [158, 119, 191]],

       [[173, 138, 159],
        [182, 117, 198]]], dtype=int32)

## Array Attribute

In [37]:
arr = np.arange(1,25).reshape(3,8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [38]:
arr.ndim

2

In [39]:
arr.shape

(3, 8)

In [40]:
arr.dtype

dtype('int64')

In [42]:
arr.size # total number of elements

24

In [43]:
arr.itemsize # each integer occupies 8 bytes

8

In [52]:
arr.nbytes # total memory size in bytes

192

In [45]:
arr2 = np.array([23,4,5,5,8.7,8])
arr2

array([23. ,  4. ,  5. ,  5. ,  8.7,  8. ])

In [48]:
arr2.dtype

dtype('float64')

In [47]:
arr2.size

6

In [49]:
arr2.itemsize

8

In [51]:
arr2.nbytes
# all attributes are part of ndarray class

48