In [1]:
import numpy as np
import time

# creating large list and array
size = 100000000
list_data = list(range(size))
array_data = np.array(range(size))

# timing of the list operation
start_time = time.time()
list_sum = sum(list_data)
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken by list: {list_time} seconds")

# timing of the array operation
start_time = time.time()
list_sum = np.sum(array_data)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken by array: {array_time} seconds")


Time taken by list: 2.355332612991333 seconds
Time taken by array: 0.061301231384277344 seconds


### In NumPy array, array is homogeneous

In [2]:
import numpy as np
ar = np.array([3,5,4,5,9.0])

In [3]:
print(type(ar[0]))

<class 'numpy.float64'>


In [4]:
ar
# numpy gives priority to floats because they can handle both whole numbers and decimal numbers

array([3., 5., 4., 5., 9.])

# Creating numpy array

In [5]:
import numpy as np
a = np.array([3,4,5])
a

array([3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [7]:
# In Numpy, ndarray is a class, and every array you create using Numpy is an instance of the ndarray class
zero = np.array(8)
zero

array(8)

In [8]:
zero.ndim

0

In [9]:
zero.shape

()

In [10]:
one = np.array([3,4,6,4,5])
one

array([3, 4, 6, 4, 5])

In [11]:
one.ndim

1

In [12]:
one.shape

(5,)

In [13]:
two = np.array([[3,4,5], [8,9,10]])
two

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [14]:
two.ndim

2

In [15]:
two.shape

(2, 3)

In [16]:
three = np.array([[[1,2,4], [4,53,4]], [[4,55,6],[7,7,58]]])
three

array([[[ 1,  2,  4],
        [ 4, 53,  4]],

       [[ 4, 55,  6],
        [ 7,  7, 58]]])

In [17]:
three.ndim

3

In [18]:
three.shape
# tensor - arrays with three or more dimensions

(2, 2, 3)

In [19]:
ara = np.arange(8) # arange function makes arrays with numbers that are evenly spaced within a set range
ara

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
ara1 = np.arange(1,8)
ara1

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
ara2 = np.arange(1,11,2)
ara2

array([1, 3, 5, 7, 9])

In [22]:
ara2 = np.arange(3,21,4)
ara2

array([ 3,  7, 11, 15, 19])

In [23]:
re = np.arange(1,21).reshape(4,5)
re

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
re1 = np.arange(1,25).reshape(6,4)
re1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [25]:
re2 = np.arange(1,25).reshape(2,4,3)
re2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [26]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
one = np.ones((4,6))
one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
lin = np.linspace(1,10,5)
lin # creates an array with 5 numbers between 1 and 10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
lin1 = np.linspace(3,20,7,dtype=int)
lin1

array([ 3,  5,  8, 11, 14, 17, 20])

In [30]:
rn = np.random.random((3,4)) # creates a 2-D array with 3 rows and 4 columns where each element ia a random float between 0 and 1
rn

array([[0.94375289, 0.10929827, 0.51092544, 0.24198517],
       [0.7185093 , 0.03187747, 0.80490634, 0.74509678],
       [0.24897326, 0.55481159, 0.37604012, 0.24777514]])

In [31]:
rn1 = np.random.random((6,3,2))
rn1

array([[[0.12086443, 0.4765763 ],
        [0.97568795, 0.78184637],
        [0.60375992, 0.04875342]],

       [[0.02152359, 0.46236366],
        [0.77032891, 0.5150641 ],
        [0.4483254 , 0.5185558 ]],

       [[0.35634231, 0.89492097],
        [0.02448579, 0.46645169],
        [0.9789024 , 0.67771641]],

       [[0.94752892, 0.08854683],
        [0.76364379, 0.57317701],
        [0.35153765, 0.77622583]],

       [[0.6152622 , 0.32109047],
        [0.74213339, 0.09169516],
        [0.18122644, 0.78129741]],

       [[0.85588605, 0.29752576],
        [0.79824928, 0.48164701],
        [0.60777679, 0.52419029]]])

In [32]:
rin = np.random.randint(1,40,12) # 12 random integers between 1 and 40
rin

array([26, 36, 29, 36, 34, 14, 37,  6, 16, 36, 15, 10], dtype=int32)

In [33]:
rint = np.random.randint(1,150,(2,3))
rint

array([[ 56,  91, 145],
       [ 98, 145,  95]], dtype=int32)

In [34]:
rint1 = np.random.randint(110,200,(5,2,3))
rint1

array([[[122, 175, 152],
        [112, 151, 164]],

       [[189, 125, 189],
        [196, 165, 119]],

       [[152, 148, 198],
        [180, 193, 136]],

       [[172, 149, 126],
        [138, 165, 161]],

       [[112, 156, 115],
        [115, 197, 171]]], dtype=int32)

## Array Attribute

In [35]:
arr = np.arange(1,25).reshape(3,8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [36]:
arr.ndim

2

In [37]:
arr.shape

(3, 8)

In [38]:
arr.dtype

dtype('int64')

In [39]:
arr.size # total number of elements

24

In [40]:
arr.itemsize # each integer occupies 8 bytes

8

In [41]:
arr.nbytes # total memory size in bytes

192

In [42]:
arr2 = np.array([23,4,5,5,8.7,8])
arr2

array([23. ,  4. ,  5. ,  5. ,  8.7,  8. ])

In [43]:
arr2.dtype

dtype('float64')

In [44]:
arr2.size

6

In [45]:
arr2.itemsize

8

In [46]:
arr2.nbytes
# all attributes are part of ndarray class

48

# Changing Datatype

In [47]:
a3 = np.array([3,4,5,6,8.0,5,6,7])
a3

array([3., 4., 5., 6., 8., 5., 6., 7.])

In [48]:
a3.astype("int") # astype() method allows you to convert an array to a different data type

array([3, 4, 5, 6, 8, 5, 6, 7])

In [49]:
a4 = np.array([93,54,75,86,8,5,6,79])
a4

array([93, 54, 75, 86,  8,  5,  6, 79])

In [50]:
a4.astype("float")

array([93., 54., 75., 86.,  8.,  5.,  6., 79.])

# Array Operations

In [51]:
import numpy as np
a1 = np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
a2 = np.arange(11,21)
a2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### scaler operation

In [54]:
a1 * 2 # 2 is scaler here

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [55]:
a1 + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
a1 - 3

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [57]:
a1 / 4

array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ])

### vector operation

In [58]:
a1 + a2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [59]:
a1 * a2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [60]:
a2 - a1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [61]:
a2 / a1

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ,
        2.66666667,  2.42857143,  2.25      ,  2.11111111,  2.        ])

### Matrix operation

In [62]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [63]:
B

array([[5, 6],
       [7, 8]])

In [64]:
add_result = A + B
add_result

array([[ 6,  8],
       [10, 12]])

In [65]:
sub_result = A - B
sub_result

array([[-4, -4],
       [-4, -4]])

In [66]:
mul_result = A * B
mul_result

array([[ 5, 12],
       [21, 32]])

In [67]:
div_result = A / B
div_result

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

## Numpy Array Mathematical function